### ISSUE TITLE
empty range for randrange() (0, 0, 0)

### ISSUE THREAD

**Issue by JaxsonYorke** [nobrien97/FortuneBot#1]
When ever I run this it gives me `empty range for randrange() (0, 0, 0)`
I think it has something to do with `len` not being a `int `but I am very new to python and not very Knowledgeable
![image_2021-09-02_004221](https://user-images.githubusercontent.com/38132640/131778352-5d9ae8f1-f5b1-490a-af15-246ed2c108d0.png)

**Comment by nobrien97** [comment]
Do you have `cowsay` and `fortune-mod` installed? I forgot to mention you need those. I've updated the readme.

**Comment by JaxsonYorke** [comment]
Yeah, the tool I was using did not work, so I switched to my personal server
